name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

    - name: Build Docker Image
      run: docker build -t my-docker-app .

    - name: Tag Docker Image
      run: docker tag my-docker-app:latest ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push Docker Image to ECR
      run: docker push ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Deploy to EC2 Instance
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_INSTANCE_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo docker pull ${{ secrets.ECR_REPOSITORY }}:latest
          sudo docker stop my-app || true
          sudo docker rm my-app || true
          sudo docker run -d --name my-app -p 80:80 ${{ secrets.ECR_REPOSITORY }}:latest
